name: family_inventory_app
description: A simple inventory tracker for home use.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  csv: ^5.0.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
